import { StyleSheet } from "react-native";
import { COLORS } from "../../../utils/colors";
import Constants from "expo-constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.secondary,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    height: 60,
    marginTop: Constants.statusBarHeight,
    backgroundColor: COLORS.secondary,
    justifyContent: "center",
  },
  return: {
    position: "absolute",
    left: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "Poppins-Medium",
  },
  content: {
    flex: 0.9,
    backgroundColor: COLORS.secondary,
    padding: 20,
    borderRadius: 10,
    marginTop: 20,
    width: "100%",
  },
  productName: {
    fontSize: 25,
    fontWeight: "bold",
    marginBottom: 10,
    fontFamily: "Poppins-Regular",
    textAlign: "center",
  },
  productLotText: {
    color: COLORS.gray_primary,
    fontFamily: "Poppins-ExtraLight",
    fontSize: 25,
  },
  productLot: {
    marginBottom: 64,
    alignItems: "center",
  },
  infoText: {
    fontSize: 22,
    marginVertical: 7,
    fontFamily: "Poppins-Regular",
  },
  label: {
    fontFamily: "Poppins-Regular",
    fontSize: 22,
  },
  quantityContainer: {
    flexDirection: "column",
    marginVertical: 10,
    width: "100%",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 20,
    marginLeft: 10,
    flex: 1,
    textAlign: "center",
    width: "100%",
    fontSize: 22,
  },
  buttonContainer: {
    marginTop: 20,
    paddingHorizontal: 24,
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  deleteButton: {
    backgroundColor: COLORS.error,
    padding: 20,
    borderRadius: 12,
    width: "100%",
  },
  editButton: {
    backgroundColor: COLORS.primary,
    padding: 20,
    borderRadius: 12,
    width: "100%",
  },
  buttonText: {
    color: COLORS.secondary,
    textAlign: "center",
    fontFamily: "Poppins-Regular",
    fontSize: 20,
  },
  labelInfo: {
    fontFamily: "Poppins-ExtraLight",
  },
  deleteButtonText: {
    color: COLORS.secondary,
    textAlign: "center",
    fontFamily: "Poppins-Regular",
    fontSize: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    width: "80%",
    backgroundColor: COLORS.secondary,
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 24,
    marginBottom: 10,
    textAlign: "center",
    fontFamily: "Poppins-Bold",
  },
  modalMessage: {
    fontSize: 18,
    textAlign: "center",
    marginBottom: 20,
    fontFamily: "Poppins-Regular",
  },
  modalInput: {
    borderWidth: 1,
    color: COLORS.primary,
    borderColor: "#ccc",
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 15,
    width: "100%",
    fontSize: 18,
    marginBottom: 20,
    textAlign: "center",
    fontFamily: "Poppins-Regular",
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
    gap: 4,
  },
  modalButton: {
    padding: 10,
    borderRadius: 5,
    width: "50%",
    alignItems: "center",
  },
  modalCancelButton: {
    backgroundColor: COLORS.gray_primary,
  },
  modalCancelButtonText: {
    color: COLORS.secondary,
    fontSize: 18,
    fontFamily: "Poppins-Regular",
  },
  modalConfirmButton: {
    backgroundColor: COLORS.error,
  },
  modalConfirmButtonText: {
    color: COLORS.secondary,
    fontSize: 18,
    fontFamily: "Poppins-Regular",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "auto",
    margin: "auto",
  },
  modalText: {
    fontSize: 16,
    marginBottom: 20,
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "red",
    padding: 10,
    borderRadius: 10,
    flex: 1,
    marginRight: 10,
    alignItems: "center",
  },
  cancelButtonText: {
    color: COLORS.secondary,
    fontSize: 18,
  },
  confirmButton: {
    backgroundColor: "black",
    padding: 10,
    borderRadius: 10,
    flex: 1,
    alignItems: "center",
  },
  confirmButtonText: {
    color: COLORS.secondary,
    fontSize: 18,
  },
});
